2015/06/06 17:50:01 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'project.pj_user_create' in 'on clause'. The SQL statement executed was: SELECT pj_id, pj_name as project,pc_code as contract,'แจ้งเตือนครบกำหนดค้ำประกันสัญญา' as alarm_detail,pc_garantee_date as date_end, CONCAT('project/update/',pj_id) as url,'1' as type, pc_id as update_id FROM project_contract pc LEFT JOIN project p ON pc.pc_proj_id=p.pj_id LEFT JOIN user ON project.pj_user_create=user.u_id WHERE DATEDIFF(pc_garantee_date,'2558-06-06')<=7  AND (pc_garantee_end='')  AND user.department_id='1'.
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (37)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 17:50:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand ล้มเหลวในการดำเนินการเรียกลักษณะของ SQL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'project.pj_user_create' in 'on clause'. The SQL statement executed was: SELECT pj_id, pj_name as project,pc_code as contract,'แจ้งเตือนครบกำหนดค้ำประกันสัญญา' as alarm_detail,pc_garantee_date as date_end, CONCAT('project/update/',pj_id) as url,'1' as type, pc_id as update_id FROM project_contract pc LEFT JOIN project p ON pc.pc_proj_id=p.pj_id LEFT JOIN user ON project.pj_user_create=user.u_id WHERE DATEDIFF(pc_garantee_date,'2558-06-06')<=7  AND (pc_garantee_end='')  AND user.department_id='1'' in C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\pea_track\protected\views\notify\_content.php(37): CDbCommand->queryAll()
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): CController->renderPartial('/notify/_conten...', Array, false)
#6 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#10 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): CController->render('index')
#11 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#12 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#17 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/pea_track/site/index
HTTP_REFERER=http://localhost/pea_track/notify/index
---
2015/06/06 18:13:44 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INNER JOIN user ON project.pj_user_create=user.u_id WHERE user.u_id = 1' at line 1. The SQL statement executed was: SELECT `t`.`pj_id`, `t`.`pj_name`, `t`.`pj_vendor_id`, `t`.`pj_work_cat`, `t`.`pj_fiscalyear`, `t`.`pj_date_approved`, `t`.`pj_user_create`, `t`.`pj_user_update`, `t`.`pj_CA`, `t`.`pj_status` FROM `project` `t` LEFT INNER JOIN user ON project.pj_user_create=user.u_id WHERE user.u_id = 1.
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (112)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 18:13:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand ล้มเหลวในการดำเนินการเรียกลักษณะของ SQL: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INNER JOIN user ON project.pj_user_create=user.u_id WHERE user.u_id = 1' at line 1. The SQL statement executed was: SELECT `t`.`pj_id`, `t`.`pj_name`, `t`.`pj_vendor_id`, `t`.`pj_work_cat`, `t`.`pj_fiscalyear`, `t`.`pj_date_approved`, `t`.`pj_user_create`, `t`.`pj_user_update`, `t`.`pj_CA`, `t`.`pj_status` FROM `project` `t` LEFT INNER JOIN user ON project.pj_user_create=user.u_id WHERE user.u_id = 1' in C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1351): CDbCommand->queryAll()
#2 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#3 C:\xampp\htdocs\pea_track\protected\views\notify\_content.php(112): CActiveRecord->findAll(Object(CDbCriteria))
#4 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): CController->renderPartial('/notify/_conten...', Array, false)
#8 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#9 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#12 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): CController->render('index')
#13 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#19 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/pea_track/site/index
HTTP_REFERER=http://localhost/pea_track/paymentOutsourceContract/admin
---
2015/06/06 18:14:34 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'project.pj_user_create' in 'on clause'. The SQL statement executed was: SELECT `t`.`pj_id`, `t`.`pj_name`, `t`.`pj_vendor_id`, `t`.`pj_work_cat`, `t`.`pj_fiscalyear`, `t`.`pj_date_approved`, `t`.`pj_user_create`, `t`.`pj_user_update`, `t`.`pj_CA`, `t`.`pj_status` FROM `project` `t` LEFT JOIN user ON project.pj_user_create=user.u_id WHERE user.u_id = 1.
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (112)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 18:14:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand ล้มเหลวในการดำเนินการเรียกลักษณะของ SQL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'project.pj_user_create' in 'on clause'. The SQL statement executed was: SELECT `t`.`pj_id`, `t`.`pj_name`, `t`.`pj_vendor_id`, `t`.`pj_work_cat`, `t`.`pj_fiscalyear`, `t`.`pj_date_approved`, `t`.`pj_user_create`, `t`.`pj_user_update`, `t`.`pj_CA`, `t`.`pj_status` FROM `project` `t` LEFT JOIN user ON project.pj_user_create=user.u_id WHERE user.u_id = 1' in C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1351): CDbCommand->queryAll()
#2 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#3 C:\xampp\htdocs\pea_track\protected\views\notify\_content.php(112): CActiveRecord->findAll(Object(CDbCriteria))
#4 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): CController->renderPartial('/notify/_conten...', Array, false)
#8 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#9 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#12 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): CController->render('index')
#13 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#19 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/pea_track/site/index
HTTP_REFERER=http://localhost/pea_track/paymentOutsourceContract/admin
---
2015/06/06 18:22:07 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JOIN user ON pj_user_create=user.u_id WHERE user.u_id = 1' at line 1. The SQL statement executed was: SELECT * FROM `project` `t` WHERE  LEFT JOIN user ON pj_user_create=user.u_id WHERE user.u_id = 1.
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (112)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 18:22:07 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand ล้มเหลวในการดำเนินการเรียกลักษณะของ SQL: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JOIN user ON pj_user_create=user.u_id WHERE user.u_id = 1' at line 1. The SQL statement executed was: SELECT * FROM `project` `t` WHERE  LEFT JOIN user ON pj_user_create=user.u_id WHERE user.u_id = 1' in C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1351): CDbCommand->queryAll()
#2 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#3 C:\xampp\htdocs\pea_track\protected\views\notify\_content.php(112): CActiveRecord->findAll(Object(CDbCriteria))
#4 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): CController->renderPartial('/notify/_conten...', Array, false)
#8 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#9 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#12 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): CController->render('index')
#13 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#19 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/pea_track/site/index
HTTP_REFERER=http://localhost/pea_track/managementCost/index?pname=%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B8%81%E0%B9%88%E0%B8%AD%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%B5%E0%B9%84%E0%B8%9F%E0%B8%9F%E0%B9%89%E0%B8%B2+%E0%B8%9B%E0%B8%B5+2558%3A%E0%B8%9A%E0%B8%A3%E0%B8%B4%E0%B8%A9%E0%B8%B1%E0%B8%97+%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%8A%E0%B9%88%E0%B8%B2%E0%B8%87&cost=1%2C000%2C000.00&ManagementCost%5Bmc_proj_id%5D=58&pj_vendor_id=%E0%B8%8A%E0%B9%88%E0%B8%B2&pid=58
---
2015/06/06 18:23:35 [error] [exception.CException] exception 'CException' with message 'CDbCriteria and its behaviors do not have a method or closure named "condition".' in C:\xampp\htdocs\pea_track\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\views\notify\_content.php(111): CComponent->__call('condition', Array)
#1 C:\xampp\htdocs\pea_track\protected\views\notify\_content.php(111): CDbCriteria->condition('user.u_id = 1')
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): CController->renderPartial('/notify/_conten...', Array, false)
#6 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#10 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): CController->render('index')
#11 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#12 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#17 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/pea_track/site/index
HTTP_REFERER=http://localhost/pea_track/managementCost/index?pname=%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B8%81%E0%B9%88%E0%B8%AD%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%B5%E0%B9%84%E0%B8%9F%E0%B8%9F%E0%B9%89%E0%B8%B2+%E0%B8%9B%E0%B8%B5+2558%3A%E0%B8%9A%E0%B8%A3%E0%B8%B4%E0%B8%A9%E0%B8%B1%E0%B8%97+%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%8A%E0%B9%88%E0%B8%B2%E0%B8%87&cost=1%2C000%2C000.00&ManagementCost%5Bmc_proj_id%5D=58&pj_vendor_id=%E0%B8%8A%E0%B9%88%E0%B8%B2&pid=58
---
2015/06/06 18:53:34 [error] [php] include(WorkCat.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\views\notify\_content.php(173): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): SiteController->renderInternal()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#4 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): SiteController->renderPartial()
#5 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#6 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): SiteController->renderInternal()
#7 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): SiteController->renderPartial()
#9 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): SiteController->render()
#10 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): SiteController->runAction()
#13 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): SiteController->runActionWithFilters()
#14 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): SiteController->run()
#15 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/site/index
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (173)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 18:53:51 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\pea_track\protected\views\notify\_content.php:174)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): SiteController->renderPartial()
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): SiteController->renderPartial()
#6 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): SiteController->render()
#7 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/site/index
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (174)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 18:54:25 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\pea_track\protected\views\notify\_content.php:175)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): SiteController->renderPartial()
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): SiteController->renderPartial()
#6 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): SiteController->render()
#7 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/site/index
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (175)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 18:54:29 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\pea_track\protected\views\notify\_content.php:175)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): SiteController->renderPartial()
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): SiteController->renderPartial()
#6 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): SiteController->render()
#7 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/site/index
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (175)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 18:54:30 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\pea_track\protected\views\notify\_content.php:175)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): SiteController->renderPartial()
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): SiteController->renderPartial()
#6 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): SiteController->render()
#7 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/site/index
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (175)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 18:54:32 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\pea_track\protected\views\notify\_content.php:175)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): SiteController->renderPartial()
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): SiteController->renderPartial()
#6 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): SiteController->render()
#7 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/site/index
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (175)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 18:54:35 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\pea_track\protected\views\notify\_content.php:175)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\pea_track\protected\views\site\index.php(21): SiteController->renderPartial()
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): SiteController->renderPartial()
#6 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): SiteController->render()
#7 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/site/index
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (175)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (21)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2015/06/06 19:13:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1433592795716
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:15:40 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1. The SQL statement executed was: SELECT COUNT(*) FROM `user` `t` WHERE department_id=.
in C:\xampp\htdocs\pea_track\protected\extensions\bootstrap\widgets\TbGridView.php (49)
in C:\xampp\htdocs\pea_track\protected\views\user\admin.php (384)
in C:\xampp\htdocs\pea_track\protected\controllers\UserController.php (169)
2015/06/06 19:15:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand ล้มเหลวในการดำเนินการเรียกลักษณะของ SQL: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1. The SQL statement executed was: SELECT COUNT(*) FROM `user` `t` WHERE department_id=' in C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php(433): CDbCommand->queryInternal('fetchColumn', 0, Array)
#1 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1601): CDbCommand->queryScalar()
#2 C:\xampp\htdocs\pea_track\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#3 C:\xampp\htdocs\pea_track\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#4 C:\xampp\htdocs\pea_track\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#5 C:\xampp\htdocs\pea_track\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#6 C:\xampp\htdocs\pea_track\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#7 C:\xampp\htdocs\pea_track\framework\zii\widgets\grid\CGridView.php(339): CBaseListView->init()
#8 C:\xampp\htdocs\pea_track\protected\extensions\bootstrap\widgets\TbGridView.php(49): CGridView->init()
#9 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(147): TbGridView->init()
#10 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(172): CBaseController->createWidget('bootstrap.widge...', Array)
#11 C:\xampp\htdocs\pea_track\protected\views\user\admin.php(384): CBaseController->widget('bootstrap.widge...', Array)
#12 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#13 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): CController->renderPartial('admin', Array, true)
#16 C:\xampp\htdocs\pea_track\protected\controllers\UserController.php(169): CController->render('admin', Array)
#17 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#18 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#21 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#23 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#24 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#25 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#26 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#27 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/index')
#28 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#29 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#30 {main}
REQUEST_URI=/pea_track/user/index
HTTP_REFERER=http://localhost/pea_track/site/index
---
2015/06/06 19:16:19 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1433592978936
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:19:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/admin
HTTP_REFERER=http://localhost/pea_track/user/create
---
2015/06/06 19:20:12 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1433593212831
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:20:23 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/admin
HTTP_REFERER=http://localhost/pea_track/user/create
---
2015/06/06 19:21:18 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1433593278091
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:22:39 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1433593359513
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:23:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('updateUser')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/updateUser')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/updateUser
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:24:23 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('updateUser')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/updateUser')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/updateUser
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:24:24 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('updateUser')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/updateUser')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/updateUser
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:24:25 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('updateUser')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/updateUser')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/updateUser
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:24:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('updateUser')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/updateUser')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/updateUser
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:24:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('updateUser')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/updateUser')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/updateUser
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:24:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('updateUser')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/updateUser')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/updateUser
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:24:28 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '???????????????...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('updateUser')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/updateUser')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/updateUser
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:30:26 [error] [exception.CException] exception 'CException' with message 'UserController and its behaviors do not have a method or closure named "isAdmin".' in C:\xampp\htdocs\pea_track\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612) : eval()'d code(1): CComponent->__call('isAdmin', Array)
#1 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612) : eval()'d code(1): UserController->isAdmin()
#2 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612): eval()
#3 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(392): CComponent->evaluateExpression('Yii::app()->con...', Array)
#4 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(288): CAccessRule->isExpressionMatched(Object(WebUser))
#5 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(138): CAccessRule->isUserAllowed(Object(WebUser), Object(UserController), Object(CInlineAction), '::1', 'GET')
#6 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#7 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#13 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#14 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1433593826719
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:30:31 [error] [exception.CException] exception 'CException' with message 'UserController and its behaviors do not have a method or closure named "isAdmin".' in C:\xampp\htdocs\pea_track\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612) : eval()'d code(1): CComponent->__call('isAdmin', Array)
#1 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612) : eval()'d code(1): UserController->isAdmin()
#2 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612): eval()
#3 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(392): CComponent->evaluateExpression('Yii::app()->con...', Array)
#4 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(288): CAccessRule->isExpressionMatched(Object(WebUser))
#5 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(138): CAccessRule->isUserAllowed(Object(WebUser), Object(UserController), Object(CInlineAction), '::1', 'POST')
#6 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#7 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('updateUser')
#13 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/updateUser')
#14 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/pea_track/user/updateUser
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:31:35 [error] [php] include(UserModule.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\components\WebUser.php(64): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\models\Notify.php(39): WebUser->isAdmin()
#2 C:\xampp\htdocs\pea_track\themes\bootstrap\views\layouts\main.php(264): Notify->getNotify()
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#4 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): UserController->renderInternal()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(784): UserController->renderFile()
#6 C:\xampp\htdocs\pea_track\protected\controllers\UserController.php(173): UserController->render()
#7 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#10 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#12 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#13 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): UserController->runActionWithFilters()
#16 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): UserController->run()
#17 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#18 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#19 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/user/index
in C:\xampp\htdocs\pea_track\protected\components\WebUser.php (64)
in C:\xampp\htdocs\pea_track\protected\models\Notify.php (39)
in C:\xampp\htdocs\pea_track\themes\bootstrap\views\layouts\main.php (264)
2015/06/06 19:33:06 [error] [exception.CException] exception 'CException' with message 'UserController and its behaviors do not have a method or closure named "isAdmin".' in C:\xampp\htdocs\pea_track\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612) : eval()'d code(1): CComponent->__call('isAdmin', Array)
#1 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612) : eval()'d code(1): UserController->isAdmin()
#2 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612): eval()
#3 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(392): CComponent->evaluateExpression('Yii::app()->con...', Array)
#4 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(288): CAccessRule->isExpressionMatched(Object(WebUser))
#5 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(138): CAccessRule->isUserAllowed(Object(WebUser), Object(UserController), Object(CInlineAction), '::1', 'GET')
#6 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#7 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#13 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#14 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1433593986122
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/06 19:33:11 [error] [exception.CException] exception 'CException' with message 'UserController and its behaviors do not have a method or closure named "isAdmin".' in C:\xampp\htdocs\pea_track\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612) : eval()'d code(1): CComponent->__call('isAdmin', Array)
#1 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612) : eval()'d code(1): UserController->isAdmin()
#2 C:\xampp\htdocs\pea_track\framework\base\CComponent.php(612): eval()
#3 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(392): CComponent->evaluateExpression('Yii::app()->con...', Array)
#4 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(288): CAccessRule->isExpressionMatched(Object(WebUser))
#5 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(138): CAccessRule->isUserAllowed(Object(WebUser), Object(UserController), Object(CInlineAction), '::1', 'POST')
#6 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#7 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('updateUser')
#13 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/updateUser')
#14 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/pea_track/user/updateUser
HTTP_REFERER=http://localhost/pea_track/user/index
---
2015/06/07 11:33:49 [warning] [application] Failed to set unsafe attribute "pc_id" of "ProjectContract".
in C:\xampp\htdocs\pea_track\protected\views\project\view.php (234)
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (129)
in C:\xampp\htdocs\pea_track\index.php (13)
2015/06/07 11:33:49 [warning] [application] Failed to set unsafe attribute "pc_details" of "ProjectContract".
in C:\xampp\htdocs\pea_track\protected\views\project\view.php (234)
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (129)
in C:\xampp\htdocs\pea_track\index.php (13)
2015/06/07 11:33:49 [warning] [application] Failed to set unsafe attribute "pc_sign_date" of "ProjectContract".
in C:\xampp\htdocs\pea_track\protected\views\project\view.php (234)
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (129)
in C:\xampp\htdocs\pea_track\index.php (13)
2015/06/07 11:33:49 [warning] [application] Failed to set unsafe attribute "pc_end_date" of "ProjectContract".
in C:\xampp\htdocs\pea_track\protected\views\project\view.php (234)
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (129)
in C:\xampp\htdocs\pea_track\index.php (13)
2015/06/07 11:33:49 [warning] [application] Failed to set unsafe attribute "pc_garantee_date" of "ProjectContract".
in C:\xampp\htdocs\pea_track\protected\views\project\view.php (234)
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (129)
in C:\xampp\htdocs\pea_track\index.php (13)
2015/06/07 11:33:49 [warning] [application] Failed to set unsafe attribute "pc_last_update" of "ProjectContract".
in C:\xampp\htdocs\pea_track\protected\views\project\view.php (234)
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (129)
in C:\xampp\htdocs\pea_track\index.php (13)
2015/06/07 11:33:49 [warning] [application] Failed to set unsafe attribute "pc_PO" of "ProjectContract".
in C:\xampp\htdocs\pea_track\protected\views\project\view.php (234)
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (129)
in C:\xampp\htdocs\pea_track\index.php (13)
2015/06/07 11:33:49 [warning] [application] Failed to set unsafe attribute "pc_name_request" of "ProjectContract".
in C:\xampp\htdocs\pea_track\protected\views\project\view.php (234)
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (129)
in C:\xampp\htdocs\pea_track\index.php (13)
2015/06/07 11:33:49 [warning] [application] Failed to set unsafe attribute "pc_code_request" of "ProjectContract".
in C:\xampp\htdocs\pea_track\protected\views\project\view.php (234)
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (129)
in C:\xampp\htdocs\pea_track\index.php (13)
